version: "3.8"
services:
    nodeserver:
        image: jakubblockczech/test
        ports:
            - "8000:8000"
    nginx:
        image: nginx
        restart: always
        ports:
            - "80:80"
