version: "3.8"
services:
    nodeserver:
        image: jakubblockczech/test
        build:
            context: ./app
        ports:
            - "8000:8000"
    nginx:
        image: jakubblockczech/test
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
